swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "Swagger Petstore"
  termsOfService: ""
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: ""
basePath: "/v1"
tags:
- name: "hello"
  description: "Everything about your Pets"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
schemes:
- "http"
paths:
  /hello:
    get:
      tags:
        - "hello"
      operationId: "hello"
      consumes:
      - "application/json"
      parameters:
      - in: "query"
        name: "word"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            items:
              $ref: "#/definitions/Hello"
        400:
          description: "Invalid status value"
definitions:
  Hello:
    type: "object"
    properties:
      response:
        type: "string"