AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  samplelambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: samplelambda/index.handler
      Runtime: nodejs6.10
      Description: ''
      MemorySize: 512
      Timeout: 15
      Events:
        LambdaMicroservice:
          Type: Api
          Properties:
            Path: /sample
            Method: ANY
  samplelambdaPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        'Fn::GetAtt':
          - samplelambda
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        'Fn::Sub': 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/*/*'
