AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  VotePost:
    Type: "AWS::Serverless::Function"
    Properties:
      Runtime: nodejs6.10
      Handler: post-vote.handler
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: $TABLE_NAME
          LOCALURL: $LOCALURL
      Events:
        Vote:
          Type: Api
          Properties:
            Path: /vote
            Method: post
  VoteGet:
    Type: "AWS::Serverless::Function"
    Properties:
      Runtime: nodejs6.10
      Handler: get-vote.handler
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: $TABLE_NAME
          LOCALURL: $LOCALURL
      Events:
        Vote:
          Type: Api
          Properties:
            Path: /vote
            Method: get